-- MySQL Script generated by MySQL Workbench
-- 11/26/15 14:18:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hehlanbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hehlanbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hehlanbd` DEFAULT CHARACTER SET utf8 ;
USE `hehlanbd` ;

-- -----------------------------------------------------
-- Table `hehlanbd`.`emplacement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`emplacement` (
  `id_emplacement` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `numero` VARCHAR(255) NOT NULL COMMENT '',
  `top` FLOAT NULL DEFAULT NULL COMMENT '',
  `xy_left` FLOAT NULL DEFAULT NULL COMMENT '',
  `width` FLOAT NULL DEFAULT NULL COMMENT '',
  `height` FLOAT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_emplacement`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 129
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`equipes` (
  `id_equipes` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nom` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL COMMENT '',
  `mot_de_passe` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `tag` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id_equipes`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hehlanbd`.`tournoi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`tournoi` (
  `id_tournoi` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nomTournoi` VARCHAR(255) NOT NULL COMMENT '',
  `joueurParTeam` INT(11) NOT NULL COMMENT '',
  `reglement` TEXT NOT NULL COMMENT '',
  `teamParMatch` INT(11) NOT NULL COMMENT '',
  `nombreManche` INT(11) NOT NULL COMMENT '',
  `nombre_joueurs_qualifies` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `heure_groupe_start` DATETIME NULL DEFAULT NULL COMMENT '',
  `heure_finale_start` DATETIME NULL DEFAULT NULL COMMENT '',
  `duree_inter_match` TIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_tournoi`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`groupes_pool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`groupes_pool` (
  `id_groupe` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_tournoi` INT(10) UNSIGNED NOT NULL COMMENT '',
  `nom_groupe` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id_groupe`)  COMMENT '',
  INDEX `id_tournoi` (`id_tournoi` ASC)  COMMENT '',
  CONSTRAINT `groupes_pool_ibfk_1`
    FOREIGN KEY (`id_tournoi`)
    REFERENCES `hehlanbd`.`tournoi` (`id_tournoi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 77
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`equipes_groupes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`equipes_groupes` (
  `id_equipe` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_groupe` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id_equipe`, `id_groupe`)  COMMENT '',
  INDEX `id_groupe` (`id_groupe` ASC)  COMMENT '',
  CONSTRAINT `equipes_groupes_ibfk_1`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `hehlanbd`.`equipes` (`id_equipes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `equipes_groupes_ibfk_2`
    FOREIGN KEY (`id_groupe`)
    REFERENCES `hehlanbd`.`groupes_pool` (`id_groupe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`joueurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`joueurs` (
  `id_joueur` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `pseudo` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `id_emplacement` INT(11) NULL DEFAULT NULL COMMENT '',
  `nom` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `prenom` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `sexe` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `gsm` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `paye` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `avatar` BLOB NULL DEFAULT NULL COMMENT '',
  `ecole` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `date_de_naissance` DATE NULL DEFAULT NULL COMMENT '',
  `level` SMALLINT(6) NOT NULL DEFAULT '5' COMMENT '',
  PRIMARY KEY (`id_joueur`)  COMMENT '',
  INDEX `id_emplacement` (`id_emplacement` ASC)  COMMENT '',
  CONSTRAINT `joueurs_ibfk_1`
    FOREIGN KEY (`id_emplacement`)
    REFERENCES `hehlanbd`.`emplacement` (`id_emplacement`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 216
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hehlanbd`.`equipes_joueur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`equipes_joueur` (
  `id_joueur_equipes` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_joueur` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_equipes` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id_joueur_equipes`)  COMMENT '',
  INDEX `id_equipes` (`id_equipes` ASC)  COMMENT '',
  INDEX `id_joueur` (`id_joueur` ASC)  COMMENT '',
  CONSTRAINT `equipes_joueur_ibfk_1`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `hehlanbd`.`joueurs` (`id_joueur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `equipes_joueur_ibfk_2`
    FOREIGN KEY (`id_equipes`)
    REFERENCES `hehlanbd`.`equipes` (`id_equipes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 323
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hehlanbd`.`equipes_tournoi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`equipes_tournoi` (
  `id_equipe` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_tournoi` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id_equipe`, `id_tournoi`)  COMMENT '',
  INDEX `id_team` (`id_tournoi` ASC)  COMMENT '',
  CONSTRAINT `equipes_tournoi_ibfk_2`
    FOREIGN KEY (`id_tournoi`)
    REFERENCES `hehlanbd`.`tournoi` (`id_tournoi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `equipes_tournoi_ibfk_3`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `hehlanbd`.`equipes` (`id_equipes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`joueurs_groupes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`joueurs_groupes` (
  `id_joueur` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_groupe` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id_joueur`, `id_groupe`)  COMMENT '',
  INDEX `id_groupe` (`id_groupe` ASC)  COMMENT '',
  CONSTRAINT `joueurs_groupes_ibfk_1`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `hehlanbd`.`joueurs` (`id_joueur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `joueurs_groupes_ibfk_2`
    FOREIGN KEY (`id_groupe`)
    REFERENCES `hehlanbd`.`groupes_pool` (`id_groupe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`joueurtournoi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`joueurtournoi` (
  `id_JT` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_joueur` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_tournoi` INT(10) UNSIGNED NOT NULL COMMENT '',
  `pseudoJeux` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id_JT`)  COMMENT '',
  INDEX `id_tournoi` (`id_tournoi` ASC)  COMMENT '',
  INDEX `id_joueur` (`id_joueur` ASC)  COMMENT '',
  CONSTRAINT `joueurtournoi_ibfk_5`
    FOREIGN KEY (`id_tournoi`)
    REFERENCES `hehlanbd`.`tournoi` (`id_tournoi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `joueurtournoi_ibfk_6`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `hehlanbd`.`joueurs` (`id_joueur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1008
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hehlanbd`.`matchs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`matchs` (
  `id_match` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_tournoi` INT(10) UNSIGNED NOT NULL COMMENT '',
  `nbr_manche` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `teamParMatch` INT(10) UNSIGNED NOT NULL DEFAULT '2' COMMENT '',
  `nom_match` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `looser_bracket` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `heure` DATETIME NULL DEFAULT NULL COMMENT '',
  `id_parent` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `id_enfant1` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `id_enfant2` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `id_groupe` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_match`)  COMMENT '',
  INDEX `id_tournoi` (`id_tournoi` ASC, `id_parent` ASC)  COMMENT '',
  INDEX `id_parent` (`id_parent` ASC)  COMMENT '',
  INDEX `id_groupe` (`id_groupe` ASC)  COMMENT '',
  INDEX `id_match_arrivee1` (`id_enfant1` ASC)  COMMENT '',
  INDEX `id_match_arrivee2` (`id_enfant2` ASC)  COMMENT '',
  CONSTRAINT `matchs_ibfk_1`
    FOREIGN KEY (`id_tournoi`)
    REFERENCES `hehlanbd`.`tournoi` (`id_tournoi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `matchs_ibfk_7`
    FOREIGN KEY (`id_parent`)
    REFERENCES `hehlanbd`.`matchs` (`id_match`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `matchs_ibfk_8`
    FOREIGN KEY (`id_enfant1`)
    REFERENCES `hehlanbd`.`matchs` (`id_match`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `matchs_ibfk_9`
    FOREIGN KEY (`id_enfant2`)
    REFERENCES `hehlanbd`.`matchs` (`id_match`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1030
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`manches_equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`manches_equipes` (
  `id_match` INT(10) UNSIGNED NOT NULL COMMENT '',
  `numero_manche` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_equipe` INT(11) UNSIGNED NOT NULL COMMENT '',
  `score` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id_match`, `numero_manche`, `id_equipe`)  COMMENT '',
  INDEX `id_equipe` (`id_equipe` ASC)  COMMENT '',
  CONSTRAINT `manches_equipes_ibfk_1`
    FOREIGN KEY (`id_match`)
    REFERENCES `hehlanbd`.`matchs` (`id_match`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `manches_equipes_ibfk_2`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `hehlanbd`.`equipes` (`id_equipes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`manches_joueurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`manches_joueurs` (
  `id_match` INT(10) UNSIGNED NOT NULL COMMENT '',
  `numero_manche` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_joueur` INT(11) UNSIGNED NOT NULL COMMENT '',
  `score` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id_match`, `numero_manche`, `id_joueur`)  COMMENT '',
  INDEX `manches_joueurs_ibfk_2` (`id_joueur` ASC)  COMMENT '',
  CONSTRAINT `manches_joueurs_ibfk_1`
    FOREIGN KEY (`id_match`)
    REFERENCES `hehlanbd`.`matchs` (`id_match`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `manches_joueurs_ibfk_2`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `hehlanbd`.`joueurs` (`id_joueur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`matchs_equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`matchs_equipes` (
  `id_match` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_equipe` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id_match`, `id_equipe`)  COMMENT '',
  INDEX `id_equipe` (`id_equipe` ASC)  COMMENT '',
  CONSTRAINT `matchs_equipes_ibfk_3`
    FOREIGN KEY (`id_match`)
    REFERENCES `hehlanbd`.`matchs` (`id_match`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `matchs_equipes_ibfk_4`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `hehlanbd`.`equipes` (`id_equipes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`matchs_joueurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`matchs_joueurs` (
  `id_match` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_joueur` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id_match`, `id_joueur`)  COMMENT '',
  INDEX `id_joueur` (`id_joueur` ASC)  COMMENT '',
  CONSTRAINT `matchs_joueurs_ibfk_1`
    FOREIGN KEY (`id_match`)
    REFERENCES `hehlanbd`.`matchs` (`id_match`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `matchs_joueurs_ibfk_2`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `hehlanbd`.`joueurs` (`id_joueur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`news` (
  `id_news` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `titre` VARCHAR(255) NOT NULL COMMENT '',
  `texte` TEXT NOT NULL COMMENT '',
  `quand` DATETIME NOT NULL COMMENT '',
  `invisible` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_news`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`sponsors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`sponsors` (
  `id_sponsor` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `logo` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `siteWeb` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_sponsor`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hehlanbd`.`tchat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`tchat` (
  `id_chat` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_joueur` INT(11) NOT NULL COMMENT '',
  `pseudo` CHAR(80) NOT NULL COMMENT '',
  `quand` DATETIME NOT NULL COMMENT '',
  `message` CHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id_chat`)  COMMENT '',
  INDEX `quand` (`quand` ASC)  COMMENT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`tchat_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`tchat_users` (
  `id_joueur` INT(11) NOT NULL COMMENT '',
  `pseudo` CHAR(80) NOT NULL COMMENT '',
  `lastcon` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id_joueur`)  COMMENT '',
  UNIQUE INDEX `id_joueur` (`id_joueur` ASC)  COMMENT '')
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hehlanbd`.`variables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`variables` (
  `nom` VARCHAR(255) NOT NULL COMMENT '',
  `valeur` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`nom`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
