-- MySQL Script generated by MySQL Workbench
-- 11/25/15 20:49:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hehlanbd
-- -----------------------------------------------------
-- Web Site and Intranet DataBase
-- 

-- -----------------------------------------------------
-- Schema hehlanbd
--
-- Web Site and Intranet DataBase
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hehlanbd` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hehlanbd` ;

-- -----------------------------------------------------
-- Table `hehlanbd`.`emplacement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`emplacement` (
  `id_emplacement` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `numero` VARCHAR(255) NOT NULL COMMENT '',
  `top` FLOAT NULL DEFAULT NULL COMMENT '',
  `xy_left` FLOAT NULL DEFAULT NULL COMMENT '',
  `width` FLOAT NULL DEFAULT NULL COMMENT '',
  `height` FLOAT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_emplacement`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`equipes` (
  `id_equipes` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nom` VARCHAR(255) NOT NULL COMMENT '',
  `mot_de_passe` VARCHAR(255) NOT NULL COMMENT '',
  `tag` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id_equipes`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`tournoi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`tournoi` (
  `id_tournoi` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nomTournoi` VARCHAR(255) NOT NULL COMMENT '',
  `joueurParTeam` INT(11) NOT NULL COMMENT '',
  `reglement` TEXT NOT NULL COMMENT '',
  `teamParMatch` INT(11) NOT NULL COMMENT '',
  `nombreManche` INT(11) NOT NULL COMMENT '',
  `nombre_joueurs_qualifies` INT(11) NOT NULL DEFAULT 1 COMMENT '',
  `heure_groupe_start` DATETIME NULL DEFAULT NULL COMMENT '',
  `heure_finale_start` DATETIME NULL DEFAULT NULL COMMENT '',
  `duree_inter_match` TIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_tournoi`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`groupes_pool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`groupes_pool` (
  `id_groupe` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_tournoi` INT(10) UNSIGNED NOT NULL COMMENT '',
  `nom_groupe` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id_groupe`)  COMMENT '',
  INDEX `fk_groupsPool_tournoi1_idx` (`id_tournoi` ASC)  COMMENT '',
  CONSTRAINT `fk_groupsPool_tournoi1`
    FOREIGN KEY (`id_tournoi`)
    REFERENCES `hehlanbd`.`tournoi` (`id_tournoi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`joueurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`joueurs` (
  `id_joueur` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `pseudo` VARCHAR(80) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `id_emplacement` INT(11) NULL DEFAULT NULL COMMENT '',
  `nom` VARCHAR(255) NOT NULL COMMENT '',
  `prenom` VARCHAR(255) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `sexe` VARCHAR(255) NOT NULL COMMENT '',
  `gsm` VARCHAR(255) NOT NULL COMMENT '',
  `paye` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `avatar` BLOB NULL DEFAULT NULL COMMENT '',
  `ecole` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `date_de_naissance` DATE NULL DEFAULT NULL COMMENT '',
  `date_inscription` DATE NOT NULL COMMENT '',
  `derniere_connexion` DATETIME NULL DEFAULT NULL COMMENT '',
  `level` SMALLINT(6) NOT NULL DEFAULT 5 COMMENT '',
  `token` TEXT NULL DEFAULT NULL COMMENT '',
  `token_validity` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_joueur`)  COMMENT '',
  INDEX `fk_joueurs_emplacement1_idx` (`id_emplacement` ASC)  COMMENT '',
  CONSTRAINT `fk_joueurs_emplacement1`
    FOREIGN KEY (`id_emplacement`)
    REFERENCES `hehlanbd`.`emplacement` (`id_emplacement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`matchs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`matchs` (
  `id_match` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_tournoi` INT(10) UNSIGNED NOT NULL COMMENT '',
  `nbr_manche` INT(11) NOT NULL DEFAULT 1 COMMENT '',
  `teamParMatch` INT(10) UNSIGNED NOT NULL DEFAULT 2 COMMENT '',
  `nom_match` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `looser_bracket` INT(11) NOT NULL DEFAULT 0 COMMENT '',
  `heure` DATETIME NULL DEFAULT NULL COMMENT '',
  `id_parent` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `id_enfant1` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `id_enfant2` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `id_groupe` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_match`)  COMMENT '',
  INDEX `fk_matchs_tournoi1_idx` (`id_tournoi` ASC)  COMMENT '',
  INDEX `fk_matchs_groupsPool1_idx` (`id_groupe` ASC)  COMMENT '',
  CONSTRAINT `fk_matchs_tournoi1`
    FOREIGN KEY (`id_tournoi`)
    REFERENCES `hehlanbd`.`tournoi` (`id_tournoi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_matchs_groupsPool1`
    FOREIGN KEY (`id_groupe`)
    REFERENCES `hehlanbd`.`groupes_pool` (`id_groupe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`news` (
  `id_news` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `titre` VARCHAR(255) NOT NULL COMMENT '',
  `texte` TEXT NOT NULL COMMENT '',
  `quand` DATETIME NOT NULL COMMENT '',
  `invisible` INT(11) NULL COMMENT '',
  PRIMARY KEY (`id_news`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`sponsors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`sponsors` (
  `id_sponsors` INT NOT NULL COMMENT '',
  `logo` VARCHAR(100) NOT NULL COMMENT '',
  `siteWeb` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `description` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_sponsors`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`tchat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`tchat` (
  `id_tchat` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_joueur` INT(11) UNSIGNED NOT NULL COMMENT '',
  `pseudo` CHAR(80) NOT NULL COMMENT '',
  `quand` DATETIME NOT NULL COMMENT '',
  `message` CHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id_tchat`)  COMMENT '',
  INDEX `fk_tchat_joueurs1_idx` (`id_joueur` ASC)  COMMENT '',
  CONSTRAINT `fk_tchat_joueurs1`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `hehlanbd`.`joueurs` (`id_joueur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`equipes_joueur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`equipes_joueur` (
  `id_joueur_equipes` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_joueur` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_equipes` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id_joueur_equipes`)  COMMENT '',
  INDEX `fk_joueurs_has_equipes_equipes1_idx` (`id_equipes` ASC)  COMMENT '',
  INDEX `fk_joueurs_has_equipes_joueurs1_idx` (`id_joueur` ASC)  COMMENT '',
  CONSTRAINT `fk_joueurs_has_equipes_joueurs1`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `hehlanbd`.`joueurs` (`id_joueur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_joueurs_has_equipes_equipes1`
    FOREIGN KEY (`id_equipes`)
    REFERENCES `hehlanbd`.`equipes` (`id_equipes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`joueurtournoi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`joueurtournoi` (
  `id_JT` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_joueur` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_tournoi` INT(10) UNSIGNED NOT NULL COMMENT '',
  `pseudoJeux` VARCHAR(255) NOT NULL COMMENT '',
  INDEX `fk_joueurs_has_tournoi_tournoi1_idx` (`id_tournoi` ASC)  COMMENT '',
  INDEX `fk_joueurs_has_tournoi_joueurs1_idx` (`id_joueur` ASC)  COMMENT '',
  PRIMARY KEY (`id_JT`)  COMMENT '',
  CONSTRAINT `fk_joueurs_has_tournoi_joueurs1`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `hehlanbd`.`joueurs` (`id_joueur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_joueurs_has_tournoi_tournoi1`
    FOREIGN KEY (`id_tournoi`)
    REFERENCES `hehlanbd`.`tournoi` (`id_tournoi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`equipes_tournoi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`equipes_tournoi` (
  `id_equipe` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_tournoi` INT(10) UNSIGNED NOT NULL COMMENT '',
  INDEX `fk_equipes_has_tournoi_tournoi1_idx` (`id_tournoi` ASC)  COMMENT '',
  INDEX `fk_equipes_has_tournoi_equipes1_idx` (`id_equipe` ASC)  COMMENT '',
  CONSTRAINT `fk_equipes_has_tournoi_equipes1`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `hehlanbd`.`equipes` (`id_equipes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_equipes_has_tournoi_tournoi1`
    FOREIGN KEY (`id_tournoi`)
    REFERENCES `hehlanbd`.`tournoi` (`id_tournoi`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`equipes_groupes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`equipes_groupes` (
  `id_equipe` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_groupe` INT(10) UNSIGNED NOT NULL COMMENT '',
  INDEX `fk_equipes_has_groupsPool_groupsPool1_idx` (`id_groupe` ASC)  COMMENT '',
  INDEX `fk_equipes_has_groupsPool_equipes1_idx` (`id_equipe` ASC)  COMMENT '',
  CONSTRAINT `fk_equipes_has_groupsPool_equipes1`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `hehlanbd`.`equipes` (`id_equipes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_equipes_has_groupsPool_groupsPool1`
    FOREIGN KEY (`id_groupe`)
    REFERENCES `hehlanbd`.`groupes_pool` (`id_groupe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`joueurs_groupes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`joueurs_groupes` (
  `id_joueur` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_groupe` INT(10) UNSIGNED NOT NULL COMMENT '',
  INDEX `fk_joueurs_has_groupsPool_groupsPool1_idx` (`id_groupe` ASC)  COMMENT '',
  INDEX `fk_joueurs_has_groupsPool_joueurs1_idx` (`id_joueur` ASC)  COMMENT '',
  CONSTRAINT `fk_joueurs_has_groupsPool_joueurs1`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `hehlanbd`.`joueurs` (`id_joueur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_joueurs_has_groupsPool_groupsPool1`
    FOREIGN KEY (`id_groupe`)
    REFERENCES `hehlanbd`.`groupes_pool` (`id_groupe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`matchs_equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`matchs_equipes` (
  `id_match` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_equipe` INT(10) UNSIGNED NOT NULL COMMENT '',
  INDEX `fk_matchs_has_equipes_equipes1_idx` (`id_equipe` ASC)  COMMENT '',
  INDEX `fk_matchs_has_equipes_matchs1_idx` (`id_match` ASC)  COMMENT '',
  CONSTRAINT `fk_matchs_has_equipes_matchs1`
    FOREIGN KEY (`id_match`)
    REFERENCES `hehlanbd`.`matchs` (`id_match`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_matchs_has_equipes_equipes1`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `hehlanbd`.`equipes` (`id_equipes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`matchs_joueurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`matchs_joueurs` (
  `id_match` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_joueur` INT(10) UNSIGNED NOT NULL COMMENT '',
  INDEX `fk_joueurs_has_matchs_matchs1_idx` (`id_match` ASC)  COMMENT '',
  INDEX `fk_joueurs_has_matchs_joueurs1_idx` (`id_joueur` ASC)  COMMENT '',
  CONSTRAINT `fk_joueurs_has_matchs_joueurs1`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `hehlanbd`.`joueurs` (`id_joueur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_joueurs_has_matchs_matchs1`
    FOREIGN KEY (`id_match`)
    REFERENCES `hehlanbd`.`matchs` (`id_match`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`sponsors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`sponsors` (
  `id_sponsors` INT NOT NULL COMMENT '',
  `logo` VARCHAR(100) NOT NULL COMMENT '',
  `siteWeb` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `description` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_sponsors`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`tchat_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`tchat_users` (
  `id_joueur` INT(11) NOT NULL COMMENT '',
  `pseudo` CHAR(80) NOT NULL COMMENT '',
  `lastcon` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id_joueur`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`variables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`variables` (
  `nom` VARCHAR(255) NOT NULL COMMENT '',
  `valeur` VARCHAR(255) NOT NULL COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`manches_equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`manches_equipes` (
  `id_match` INT(10) UNSIGNED NOT NULL COMMENT '',
  `numero_manche` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_equipe` INT(11) UNSIGNED NOT NULL COMMENT '',
  `score` INT(11) NOT NULL DEFAULT 0 COMMENT '',
  INDEX `fk_matchs_has_equipes_equipes2_idx` (`id_equipe` ASC)  COMMENT '',
  INDEX `fk_matchs_has_equipes_matchs2_idx` (`id_match` ASC)  COMMENT '',
  CONSTRAINT `fk_matchs_has_equipes_matchs2`
    FOREIGN KEY (`id_match`)
    REFERENCES `hehlanbd`.`matchs` (`id_match`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_matchs_has_equipes_equipes2`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `hehlanbd`.`equipes` (`id_equipes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hehlanbd`.`manches_joueurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hehlanbd`.`manches_joueurs` (
  `id_match` INT(10) UNSIGNED NOT NULL COMMENT '',
  `numero_manche` INT(10) UNSIGNED NOT NULL COMMENT '',
  `id_joueur` INT(11) UNSIGNED NOT NULL COMMENT '',
  `score` INT(11) NOT NULL DEFAULT 0 COMMENT '',
  INDEX `fk_matchs_has_joueurs_joueurs1_idx` (`id_joueur` ASC)  COMMENT '',
  INDEX `fk_matchs_has_joueurs_matchs1_idx` (`id_match` ASC)  COMMENT '',
  CONSTRAINT `fk_matchs_has_joueurs_matchs1`
    FOREIGN KEY (`id_match`)
    REFERENCES `hehlanbd`.`matchs` (`id_match`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_matchs_has_joueurs_joueurs1`
    FOREIGN KEY (`id_joueur`)
    REFERENCES `hehlanbd`.`joueurs` (`id_joueur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
